#!/bin/bash

# rvry v 1.1.0
# ©2022 barcek
# License: MIT
# @ github.com
# /barcek/rvry

mark=.
path=0
beat=1
sign=q

if ! [ -z "$1" ]; then
  tag=$1
fi

if ! [ -z "$2" ]; then
  log=$2
  dt0=$(date)
fi

heed() {
  read -t $beat -N 1 char
  if [ $sign == "$char" ]; then
    wake
  fi
}

step() {
  echo -n $mark
  ((path++))
}

form() {
  secs=$((path*$beat))
  view=$(printf "%02d:%02d:%02d" $(($secs%86400/3600)) $(($secs%3600/60)) $(($secs%60)))
  if [ -n "$tag" ]; then
    view+=" ${tag}"
  fi
  echo "${view}"
}

keep() {
  if [ -n "$log" ]; then
    echo $dt0 $1 >> $log
  fi
}

show() {
  wipe="\033[2K\r"
  echo -ne $wipe
  echo $1
}

wake() {
  view=$(form)
  keep "$view"
  show "$view"
  exit 1
}

trap "wake" SIGINT

while [ true ]; do
  heed
  step
done
